@startuml
class Database {
database_directory: Path
----
__init__(database_directory)
create_attendance(attendance: Attendance)
update_attendance(attendance: Attendance)
get_attendance(id: str): Attendance
get_get_summary_attendance(): List[str]
delete_attendance(id: str) # NOT IMPLEMENTED
}


struct Attendance {
id: str
records: List [StudentAttendanceItem]
}

struct StudentAttendanceItem {
studentID: str
isPresent: bool
}

Database   *---- Attendance
Attendance *---- StudentAttendanceItem
@enduml